### PR TITLE
Added an always daylight toggle to cameras

### PR DESCRIPTION
**Pull request by drdozer**
I have done a minimal change to add the UX and implementation for a toggle to screenshots being taken in daylight. When the flag is true, the old behaviour of taking screenshots in forced daylight is kept. When set to false, it allows the screenshot routine to use the current gameplay daytime. As legacy cameras would have this field missing, I have added a migration to set it to true. I have not bumped the mod version number, but I think this is required to make the migration script trigger. I've tested in some of my games, and it appears to function as advertised for me.

### CODE REVIEW

**Comment by veger** [comment]
Thanks a lot for your contribution, on a first/quick sight it looks ok.

But the original requester wanted to make timelapses at night, with your change it will have the day/night cycle.

Having day/night cycles though can be kinda cool as well, so maybe a dropdown with the 3 choices would be a perfect solution!

**Comment by drdozer** [comment]
What would we set the daytime to so that it is night?

**Comment by drdozer** [comment]
I've re-read the original request, and I think they were asking for always day vs track the actual daytime daylight. I don't think they were asking to be able to set it to always night.

**Comment by veger** [comment]
> What would we set the daytime to so that it is night?

I assume setting it 6250 (half of a day duration) should work? :thinking:  (see https://wiki.factorio.com/Time)

> I've re-read the original request, and I think they were asking for always day vs track the actual daytime daylight. I don't think they were asking to be able to set it to always night.

You might be right, the 'taken as is' would point to this direction I guess...

I'll try you changes soon, and merge when it all indeed works :smile:

**Comment by drdozer** [comment]
Great. If/when it is merged I can do essentially the same edits to toggle the GUI in screenshots. Default off.

**Comment by drdozer** [comment]
bump?

**Comment by veger** [comment]
sorry for the lack of response, IRL happened... I am going to try/test it right away!

**Comment by drdozer** [comment]
Not a problem. My life is one long series of often-overlapping IRL happenings. If this pull request is OK then I'll add some support for some other snapshot flags.

**Comment by veger** [comment]
I changed some comments and added your name in the changelog (assuming you are ok, I'll merge)

**Comment by drdozer** [comment]
That's all fine by  me :) Cheers.

**Pull request merged**
